### ISSUE TITLE
Links inside pages not working with touch devices

### ISSUE THREAD

**Issue by robindevouge** [Mobius1/Pageable#14]
Hi!

I noticed that with a touch input (either with a mobile device or Chrome responsive emulation) clicking on a link doesn't work unless you "double touch" it.

However, this doesn't happen if you set touch events to false on initialisation, so I thought this was caused by Pageable catching the touch to swipe thus preventing to trigger the link's.

This behaviour can be replicated in the playground by replacing a page text with a link while in responsive mode in chrome.

If anyone else reading this is affected by this issue and looking for a temporary solution : I fixed it with some JS by adding a listener on the affected links that redirects to their url but that isn't ideal
```
Array.from(document.querySelectorAll('.myLink')).forEach((el) => {
  el.addEventListener('touchend', () => {
    window.location.href = el.href;
  });
});
```

**Comment by conhuynh** [comment]
I'm also having this issue. 

I've had to add in some extra buttons that appear on touch devices to get around this bug for now.

**Comment by Mobius1** [comment]
I'll get a fix out for this ASAP.

**Comment by GiorgosK** [comment]
Confirm the same problem first comment was very helpful

**Comment by Mobius1** [comment]
A fix should be out soon.

**Comment by ValeriiMetlenok** [comment]
fixed that after commented this two strings
![1](https://user-images.githubusercontent.com/23419557/57822626-8af03380-77be-11e9-9a53-395bf683b356.png)

**Comment by arnulphus** [comment]
> fixed that after commented this two strings
> ![1](https://user-images.githubusercontent.com/23419557/57822626-8af03380-77be-11e9-9a53-395bf683b356.png)

Works great with it!!

**Comment by StevenJW** [comment]
> fixed that after commented this two strings
> ![1](https://user-images.githubusercontent.com/23419557/57822626-8af03380-77be-11e9-9a53-395bf683b356.png)

It does work but it makes the animation glitch, as if you could scroll freely.

**Comment by piotrku** [comment]
This is some solution @ValeriiMetlenok thanks for that, but is there a chance for a real solution anytime soon?
@Mobius1 - thanks for the script anyway - very useful :)

**Comment by juliomotol** [comment]
Has this been fixed yet? I'm still having this issue as of v0.6.8

> ```
> Array.from(document.querySelectorAll('.myLink')).forEach((el) => {
>   el.addEventListener('touchend', () => {
>     window.location.href = el.href;
>   });
> });
> ```

and also this fix makes an animation glitch that slides to the most bottom slide then popping back to the actual anchor.

**Comment by aleksandrp** [comment]
Same trouble on inside scroll and buttons. NAV container works fine...

**Comment by junok44** [comment]
im noob. i can't understand..  can you teach me more easily?

**Comment by teddyh-io** [comment]
Desperately wanted @ValeriiMetlenok 's function to work, but it completely broke scrolling as @StevenJW said. @robindevouge 's solution takes you to the link even if you are trying to move between pages.
This should detect drag and only take you to links if there is no drag.
```
var isDragging = false;
jQuery(window)
.touchmove(function(e) {
    isDragging = true;
 })
.touchend(function(e) {
    var wasDragging = isDragging;
    if (!wasDragging) {
    window.location.href = jQuery(e.target).attr("href");
    }
    isDragging = false;
});
```

**Comment by channprj** [comment]
Thank you for all!

**Comment by juniorrumbelow** [comment]
<img width="932" alt="Screen Shot 2023-03-25 at 15 47 10" src="https://user-images.githubusercontent.com/13964104/227727779-c1146c3a-f50d-45c8-8fb9-ab48f1317565.png">

You can add in a checks on the `e.target.nodeName` to ignore those elements e.g buttons and links, seems to work for me
